### ISSUE TITLE
Starting framework with marathon event bus error: Hostname verification failed

### ISSUE THREAD

**Issue by shangd** [GalacticFog/gestalt-dcos#8]
I'm running a local dcos cluster ([this](https://github.com/dcos/dcos-vagrant)) on my machine with the suggested framework config
https://github.com/GalacticFog/gestalt-dcos/issues/7#issuecomment-349996649

The hostname name used for the msg bus connection seems to be coming from the env var `MARATHON_URL`

I tried `leader.mesos`, `m1.dcos` and raw ip, all lead to the same error. 

```
2017-12-20 01:23:55,921 [DEBUG] from akka.io.TcpOutgoingConnection in application-akka.actor.default-dispatcher-94 - Resolving 192.168.65.90 before connecting
2017-12-20 01:23:55,921 [DEBUG] from akka.io.TcpOutgoingConnection in application-akka.actor.default-dispatcher-94 - Attempting connection to [/192.168.65.90:443]
2017-12-20 01:23:56,015 [DEBUG] from akka.io.TcpOutgoingConnection in application-akka.actor.default-dispatcher-92 - Connection established to [192.168.65.90:443]
2017-12-20 01:23:56,120 [DEBUG] from akka.stream.impl.io.TLSActor in application-akka.actor.default-dispatcher-88 - closing output
2017-12-20 01:23:56,120 [DEBUG] from akka.actor.RepointableActorRef in application-akka.actor.default-dispatcher-91 - Aborting tcp connection to 192.168.65.90:443 because of upstream failure: Hostname verification failed! Expected session to be for 192.168.65.90
2017-12-20 01:23:56,121 [INFO] from com.galacticfog.gestalt.dcos.marathon.MarathonSSEClient in application-akka.actor.default-dispatcher-91 - failure connecting to marathon event bus
akka.stream.ConnectionException: Hostname verification failed! Expected session to be for 192.168.65.90
2017-12-20 01:23:56,122 [ERROR] from com.galacticfog.gestalt.dcos.launcher.LauncherFSM in application-akka.actor.default-dispatcher-88 - received Failure status from Marathon event bus, will attempt to reconnect: java.lang.RuntimeException: error connecting to Marathon event bus
	at com.galacticfog.gestalt.dcos.marathon.MarathonSSEClient$$anonfun$connectToBus$2.apply(MarathonSSEClient.scala:131)
	at com.galacticfog.gestalt.dcos.marathon.MarathonSSEClient$$anonfun$connectToBus$2.apply(MarathonSSEClient.scala:123)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: akka.stream.ConnectionException: Hostname verification failed! Expected session to be for 192.168.65.90
```

changing it to http doesnt work either:
```
Caused by: akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: text/event-stream
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:155)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:111)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:108)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.LowerPriorityGenericUnmarshallers$$anonfun$messageUnmarshallerFromEntityUnmarshaller$1$$anonfun$apply$1$$anonfun$apply$2.apply(GenericUnmarshallers.scala:25)
	at akka.http.scaladsl.unmarshalling.LowerPriorityGenericUnmarshallers$$anonfun$messageUnmarshallerFromEntityUnmarshaller$1$$anonfun$apply$1$$anonfun$apply$2.apply(GenericUnmarshallers.scala:25)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:19)
	at com.galacticfog.gestalt.dcos.marathon.MarathonSSEClient$$anonfun$connectToBus$1.apply(MarathonSSEClient.scala:122)
	at com.galacticfog.gestalt.dcos.marathon.MarathonSSEClient$$anonfun$connectToBus$1.apply(MarathonSSEClient.scala:122)
```

Is there a workaround for this?

**Comment by cgbaker** [comment]
Set the `MARATHON_URL` variable to `http://m1.dcos:8080`

**Comment by shangd** [comment]
@cgbaker cool got it working using `http://m1.dcos:8080`, thanks!
